version: '3.1'

services:
  otrs:
    image: juanluisbaptiste/otrs:latest
    container_name: znuny_otrs
    env_file: .env
    secrets:
      - otrs_secrets
    volumes:
      - ./volumes/config:/opt/otrs/Kernel
      - ./volumes/skins:/opt/otrs/var/httpd/htdocs/skins/
      - ./backups:/var/otrs/backups
      - ./volumes/addons:/opt/otrs/addons
      - ./volumes/db_upgrade:/opt/otrs/db_upgrade
      - /etc/localtime:/etc/localtime:ro
    networks:
      - nmqnet
    restart: unless-stopped

secrets:
  otrs_secrets:
    file: ./secrets/otrs_secrets

networks:
  nmqnet:
    external: true
